# Generated by Django 3.2 on 2021-04-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ask',
            new_name='Task',
        ),
    ]
